### ISSUE TITLE
Cannot open database "Kentico" requested by the login. The login failed.

### ISSUE THREAD

**Issue by thinnv** [Kentico/Mvc#18]
I do follow to Readme but error 

![image](https://cloud.githubusercontent.com/assets/6780364/21599078/727f982c-d199-11e6-9c1e-b5e4c8060d7e.png)

I config file  Config: 
![image](https://cloud.githubusercontent.com/assets/6780364/21599088/8f76b104-d199-11e6-928c-cfba4a7d4b4c.png)

Please support for me. Thanks

**Comment by makma** [comment]
Do you have correct credentials? Is it possible to connect with these credentials to db  (eg via SQL server mngmt studio)? If so, do you have proper app pool for your app?

**Comment by thinnv** [comment]
I do some steps following: 
Step 1: install Kentico 10.
Step 2: I run local 
![image](https://cloud.githubusercontent.com/assets/6780364/21603304/c52c482e-d1ce-11e6-9b28-9eca20b0f698.png)

Step 3: I configed  CMSConnectionString of KenticoMvc DancingGoat Project With DB Created but DB not match. Could you  write for   setuping tutorial to run and build it? 
Thanks you.

**Comment by makma** [comment]
Could you try to copy-paste your exact connection string from Kentico instance to you MVC DancingGoat project? Make sure you are using the same application pool as well. 

Note: You can find instructions in [Readme.md](https://github.com/Kentico/Mvc/blob/master/Readme.md)

**Comment by rpribyl** [comment]
Closing the issue as there are wasn't any update for the last 14 days.
