### ISSUE TITLE
siteName Error

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/Mvc#24]
Original issue: https://github.com/Kentico/Home/issues/2 submitted by https://github.com/mdaniels-chl

Went through the steps for both Learning Kit and Dancing Goat and both get an error. 
![screen shot 2017-04-05 at 5 11 44 pm](https://cloud.githubusercontent.com/assets/20323862/24729268/00e34cea-1a23-11e7-8018-85973242afb7.png)

**Comment by mdaniels-chl** [comment]
Issue is resolved and can be closed.
